#!/usr/bin/env bash
#performing a 301 moved permanently

sudo apt-get update
sudo apt-get install -y nginx

echo "Holberton School" | sudo tee /var/www/html/index.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/bakudbilla permanent;"

sudo sed -i "s/server_name _;/$string_for replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
